package com.sample.rules
 
import com.sample.DroolsTest.GUI;

declare Question
	question_content : String @key
	answer : String
end

// when	pytanie poprzedne zadane i ma konkretną odpowiedź to zapytaj nastepne lub udziel odp

global GUI gui

rule "1"
		when
		then
			String question = "Want your night to be action packed?";
            String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end
rule "2"
		when
			Question(question_content == "Want your night to be action packed?", answer == "Yes")
		then
			String question = "Have you seen a Terminator?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "3"
		when
			Question(question_content == "Want your night to be action packed?", answer == "No")
		then
			String question = "What about a documentary?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "4"
		when
			Question(question_content == "Have you seen a Terminator?", answer == "Yes")
		then
			String movie = "Terminator 2: Judgment Day";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "5"
		when
			Question(question_content == "Have you seen a Terminator?", answer == "No")
		then
			String question = "How about a war movie?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "6"
		when
			Question(question_content == "How about a war movie?", answer == "Yes")
		then
			String movie = "Black Hawk Down";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "7"
		when
			Question(question_content == "How about a war movie?", answer == "No")
		then
			String question = "Horses, boots and 10-gallon hats?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "8"
		when
			Question(question_content == "Horses, boots and 10-gallon hats?", answer == "Yes")
		then
			String question = "You want to go oldschool or keep it fresh?";
			String[] possible_answers = {"Old", "Fresh"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "9"
		when
			Question(question_content == "You want to go oldschool or keep it fresh?", answer == "Old")
		then
			String movie = "One Upon a Time in the West";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "10"
		when
			Question(question_content == "You want to go oldschool or keep it fresh?", answer == "Fresh")
		then
			String movie = "True Grit";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "11"
		when
			Question(question_content == "Horses, boots and 10-gallon hats?", answer == "No")
		then
			String question = "Do you want to keep it serious?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "12"
		when
			Question(question_content == "Do you want to keep it serious?", answer == "No")
		then
			String movie = "Top Gun";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "13"
		when
			Question(question_content == "Do you want to keep it serious?", answer == "Yes")
		then
			String question = "Set in the future or present day?";
			String[] possible_answers = {"Future", "Now"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "14"
		when
			Question(question_content == "Set in the future or present day?", answer == "Future")
		then
			String movie = "Aeon Flux";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "15"
		when
			Question(question_content == "Set in the future or present day?", answer == "Now")
		then
			String movie = "Shooter";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "16"
		when
			Question(question_content == "What about a documentary?", answer == "Yes")
		then
			String question = "Do you consider snowboard films to be documentaries?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "17"
		when
			Question(question_content == "Do you consider snowboard films to be documentaries?", answer == "Yes")
		then
			String movie = "Art of Flight";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "18"
		when
			Question(question_content == "Do you consider snowboard films to be documentaries?", answer == "No")
		then
			String question = "Do you want to have your face melted off from maxiumum rock?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "19"
		when
			Question(question_content == "Do you want to have your face melted off from maxiumum rock?", answer == "Yes")
		then
			String movie = "Year of the Horse";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "20"
		when
			Question(question_content == "Do you want to have your face melted off from maxiumum rock?", answer == "No")
		then
			String question = "Take it to the streets?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "21"
		when
			Question(question_content == "Take it to the streets?", answer == "Yes")
		then
			String question = "Pain or Paint?";
			String[] possible_answers = {"Pain", "Paint"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "22"
		when
			Question(question_content == "Pain or Paint?", answer == "Pain")
		then
			String movie = "Bones Brigade: An Autobiography";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "23"
		when
			Question(question_content == "Pain or Paint?", answer == "Paint")
		then
			String movie = "Exit Through the Gift Shop";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "24"
		when
			Question(question_content == "Take it to the streets?", answer == "No")
		then
			String question = "Do you want to see how ridiculous religion can be?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "25"
		when
			Question(question_content == "Do you want to see how ridiculous religion can be?", answer == "Yes")
		then
			String movie = "Religulous";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "26"
		when
			Question(question_content == "Do you want to see how ridiculous religion can be?", answer == "No")
		then
			String question = "Are you a Woody Allen fan? Or would you like to become one?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "27"
		when
			Question(question_content == "Are you a Woody Allen fan? Or would you like to become one?", answer == "Yes")
		then
			String movie = "Woody Allen: A Documentary";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "28"
		when
			Question(question_content == "Are you a Woody Allen fan? Or would you like to become one?", answer == "No")
		then
			String question = "Do subtitles bother you?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "29"
		when
			Question(question_content == "Do subtitles bother you?", answer == "Yes")
		then
			String movie = "Grizzly man";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "30"
		when
			Question(question_content == "Do subtitles bother you?", answer == "No")
		then
			String movie = "Man on Wire";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "31"
		when
			Question(question_content == "What about documentary?", answer == "No")
		then
			String question = "Monsters, murderers and madness?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);
end

rule "32"
		when
			Question(question_content == "Monsters, murderers and madness?", answer == "Yes")
		then
			String question = "Should there be a blood saoked chainsaw at some point?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);
end
		

rule "33"
	when
			Question(question_content == "Should there be a blood saoked chainsaw at some point?", answer == "Yes")
		then
			String movie = "The Evil dead";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end
		
rule "34"
	when
		Question(question_content == "Should there be a blood saoked chainsaw at some point?", answer == "No")
	then
		String question = "Three parts classic horror, one part something new?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);
end

rule "35"
	when
		Question(question_content == "Three parts classic horror, one part something new?", answer == "Yes")
	then
		String movie = "Cabin in the woods";
		gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "36"
	when
		Question(question_content == "Three parts classic horror, one part something new?", answer == "No")
	then
		String question = "Do abandoned asylums scare the sense out of you?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);
end

rule "37"
	when
		Question(question_content == "Do abandoned asylums scare the sense out of you?", answer == "Yes")
	then
		String movie = "Session 9";
		gui.insertQuestionAndSetAnswer(movie, null, true);
end
	
rule "38"
	when
		Question(question_content == "Do abandoned asylums scare the sense out of you?", answer == "No")
	then
		String movie = "Insidious";
		gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "39"
		when
			Question(question_content == "Monsters, murderers and madness?", answer == "No")
		then
			String question = "Are you in the mood to laugh?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);
end

rule "40"
	when
		Question(question_content == "Are you in the mood to laugh?", answer == "Yes")
	then
		String question = "Do you want some drama with your laughter?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "41"
	when
		Question(question_content == "Do you want some drama with your laughter?", answer == "No")
	then
		String question = "Do you mind it when people break out singing?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "42"
	when
		Question(question_content == "Do you mind it when people break out singing?", answer == "Yes")
	then
		String movie = "Happy Gilmore";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "43"
	when
		Question(question_content == "Do you mind it when people break out singing?", answer == "No")
	then
		String question = "Do you find clever worldplay entertaining?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "44"
	when
		Question(question_content == "Do you find clever worldplay entertaining?", answer == "Yes")
	then
		String movie = "Duck Soup";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "45"
	when
		Question(question_content == "Do you find clever worldplay entertaining?", answer == "No")
	then
		String movie = "Ferris Bueller's Day Off";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "46"
	when
		Question(question_content == "Do you want some drama with your laughter?", answer == "Yes")
	then
		String question = "Are you adverse to black and white?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "47"
	when
		Question(question_content == "Are you adverse to black and white?", answer == "Yes")
	then
		String question = "Do you love Paul Newman? Do you want to?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "48"
	when
		Question(question_content == "Do you love Paul Newman? Do you want to?", answer == "Yes")
	then
		String question = "Do you want to watch something great or legendary?";
		String[] possible_answers = {"Legend", "Great"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "49"
	when
		Question(question_content == "Do you want to watch something great or legendary?", answer == "Legend")
	then
		String movie = "Butch Cassidy and the Sundance Kid";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "50"
	when
		Question(question_content == "Do you want to watch something great or legendary?", answer == "Great")
	then
		String movie = "Slap Shot";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "51"
	when
		Question(question_content == "Do you love Paul Newman? Do you want to?", answer == "No")
	then
		String question = "Gritty or pretty?";
		String[] possible_answers = {"Gritty", "Pretty"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "52"
	when
		Question(question_content == "Gritty or pretty?", answer == "Gritty")
	then
		String movie = "Transpotting";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "53"
	when
		Question(question_content == "Gritty or pretty?", answer == "Pretty")
	then
		String question = "Slow-paces quirky romantic indie?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "54"
	when
		Question(question_content == "Slow-paces quirky romantic indie?", answer == "Yes")
	then
		String movie = "Lost in Translation";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "55"
	when
		Question(question_content == "Slow-paces quirky romantic indie?", answer == "No")
	then
		String movie = "Big Fish";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "56"
	when
		Question(question_content == "Are you adverse to black and white?", answer == "No")
	then
		String question = "Do you like your humor to e less or more lewd?";
		String[] possible_answers = {"Less", "More"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "57"
	when
		Question(question_content == "Do you like your humor to e less or more lewd?", answer == "Less")
	then
		String movie = "ManHattan";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "58"
	when
		Question(question_content == "Do you like your humor to e less or more lewd?", answer == "More")
	then
		String movie = "Clerks";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "59"
	when
		Question(question_content == "Are you in the mood to laugh?", answer == "No")
	then
		String question = "Do you hunger for adventure?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "60"
	when
		Question(question_content == "Do you hunger for adventure?", answer == "Yes")
	then
		String question = "Were you a fan of Firefly?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);
	
end
rule "61"
	when
		Question(question_content == "Were you a fan of Firefly?", answer == "Yes")
	then
		String movie = "Serenity";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "62"
	when
		Question(question_content == "Were you a fan of Firefly?", answer == "No")
	then
		String question = "Do you like main roles to be played by kids?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "63"
	when
		Question(question_content == "Do you like main roles to be played by kids?", answer == "Yes")
	then
		String question = "Want some thrills with your adventure?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "64"
	when
		Question(question_content == "Want some thrills with your adventure?", answer == "Yes")
	then
		String movie = "Super 8";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "65"
	when
		Question(question_content == "Want some thrills with your adventure?", answer == "No")
	then
		String movie = "The Hunger Games";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "66"
	when
		Question(question_content == "Do you like main roles to be played by kids?", answer == "No")
	then
		String movie = "Star Trek II: The Wrath of Khan";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "67"
	when
		Question(question_content == "Do you hunger for adventure?", answer == "No")
	then
		String question = "Care for some criminal intent?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "68"
	when
		Question(question_content == "Care for some criminal intent?", answer == "Yes")
	then
		String question = "Do you enjoy diatribes entirely unrelated to the plot?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "69"
	when
		Question(question_content == "Do you enjoy diatribes entirely unrelated to the plot?", answer == "Yes")
	then
		String movie = "Reservoir Dogs";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "70"
	when
		Question(question_content == "Do you enjoy diatribes entirely unrelated to the plot?", answer == "No")
	then
		String question = "Are you upser by seeing drug use?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "71"
	when
		Question(question_content == "Are you upser by seeing drug use?", answer == "Yes")
	then
		String question = "Mob story?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "72"
	when
		Question(question_content == "Mob story?", answer == "Yes")
	then
		String movie = "Miller's Crossing";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "73"
	when
		Question(question_content == "Mob story?", answer == "No")
	then
		String movie = "Clay Pigeons";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "74"
	when
		Question(question_content == "Are you upser by seeing drug use?", answer == "No")
	then
		String question = "Do you love hip hop?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "75"
	when
		Question(question_content == "Do you love hip hop?", answer == "Yes")
	then
		String movie = "Hustle & Flow";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "76"
	when
		Question(question_content == "Do you love hip hop?", answer == "No")
	then
		String movie = "Traffic";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "77"
	when
		Question(question_content == "Care for some criminal intent?", answer == "No")
	then
		String question = "Ready for some romance?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "78"
	when
		Question(question_content == "Ready for some romance?", answer == "Yes")
	then
		String question = "Tom Cruise of Matt Damon?";
		String[] possible_answers = {"Tom", "Matt"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "79"
	when
		Question(question_content == "Tom Cruise of Matt Damon?", answer == "Tom")
	then
		String movie = "Vanilla Sky";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "80"
	when
		Question(question_content == "Tom Cruise of Matt Damon?", answer == "Matt")
	then
		String movie = "Good Will Hunting";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "81"
	when
		Question(question_content == "Ready for some romance?", answer == "No")
	then
		String question = "Hypothetically: would a long brutal rape scene ruin your night?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "82"
	when
		Question(question_content == "Hypothetically: would a long brutal rape scene ruin your night?", answer == "Yes")
	then
		String question = "Do you want to be completely confused?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);
	
end
rule "83"
	when
		Question(question_content == "Do you want to be completely confused?", answer == "Yes")
	then
		String movie = "Pi";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "84"
	when
		Question(question_content == "Do you want to be completely confused?", answer == "No")
	then
		String question = "Are sutitles going to be a problem?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "85"
	when
		Question(question_content == "Are sutitles going to be a problem?", answer == "Yes")
	then
		String question = "Keep it mellow?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "86"
	when
		Question(question_content == "Keep it mellow?", answer == "Yes")
	then
		String movie = "Midnight Cowboy";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "87"
	when
		Question(question_content == "Keep it mellow?", answer == "No")
	then
		String movie = "The Machinist";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "88"
	when
		Question(question_content == "Are sutitles going to be a problem?", answer == "No")
	then
		String movie = "Tomboy";
		gui.insertQuestionAndSetAnswer(movie, null, true);
		
end
rule "89"
	when
		Question(question_content == "Hypothetically: would a long brutal rape scene ruin your night?", answer == "No")
	then
		String question = "Have you seen the original Girl with the Dragon Tattoo?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "90"
	when
		Question(question_content == "Have you seen the original Girl with the Dragon Tattoo?", answer == "Yes")
	then
		String question = "Have you seen The Girl Who Played with Fire?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

end
rule "91"
	when
		Question(question_content == "Have you seen The Girl Who Played with Fire?", answer == "Yes")
	then
		String movie = "The Girl who Kicked the Hornet's Nest";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "92"
	when
		Question(question_content == "Have you seen The Girl Who Played with Fire?", answer == "No")
	then
		String movie = "The Girl who Played with Fire";
		gui.insertQuestionAndSetAnswer(movie, null, true);

end
rule "93"
	when
		Question(question_content == "Have you seen the orginal Girl with the Dragon Tatoo?", answer == "No")
	then
		String movie = "The Girl with the Dragon Tatoo";
		gui.insertQuestionAndSetAnswer(movie, null, true);
end