package com.sample.rules
 
import com.sample.DroolsTest.GUI;

declare Question
	question_content : String @key
	answer : String
end

// when	pytanie poprzedne zadane i ma konkretną odpowiedź to zapytaj nastepne lub udziel odp

global GUI gui

rule "1"
		when
		then
			String question = "Want your night to be action packed?";
            String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end
rule "2"
		when
			Question(question_content == "Want your night to be action packed?", answer == "Yes")
		then
			String question = "Have you seen a Terminator?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "3"
		when
			Question(question_content == "Want your night to be action packed?", answer == "No")
		then
			String question = "What about a documentary?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "4"
		when
			Question(question_content == "Have you seen a Terminator?", answer == "Yes")
		then
			String movie = "Terminator 2: Judgment Day";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "5"
		when
			Question(question_content == "Have you seen a Terminator?", answer == "No")
		then
			String question = "How about a war movie?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "6"
		when
			Question(question_content == "How about a war movie?", answer == "Yes")
		then
			String movie = "Black Hawk Down";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "7"
		when
			Question(question_content == "How about a war movie?", answer == "No")
		then
			String question = "Horses, boots and 10-gallon hats?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "8"
		when
			Question(question_content == "Horses, boots and 10-gallon hats?", answer == "Yes")
		then
			String question = "You want to go oldschool or keep it fresh?";
			String[] possible_answers = {"Old", "Fresh"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "9"
		when
			Question(question_content == "You want to go oldschool or keep it fresh?", answer == "Old")
		then
			String movie = "One Upon a Time in the West";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "10"
		when
			Question(question_content == "You want to go oldschool or keep it fresh?", answer == "Fresh")
		then
			String movie = "True Grit";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "11"
		when
			Question(question_content == "Horses, boots and 10-gallon hats?", answer == "No")
		then
			String question = "Do you want to keep it serious?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "12"
		when
			Question(question_content == "Do you want to keep it serious?", answer == "No")
		then
			String movie = "Top Gun";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "13"
		when
			Question(question_content == "Do you want to keep it serious?", answer == "Yes")
		then
			String question = "Set in the future or present day?";
			String[] possible_answers = {"Future", "Now"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "14"
		when
			Question(question_content == "Set in the future or present day?", answer == "Future")
		then
			String movie = "Aeon Flux";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "15"
		when
			Question(question_content == "Set in the future or present day?", answer == "Now")
		then
			String movie = "Shooter";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "16"
		when
			Question(question_content == "What about a documentary?", answer == "Yes")
		then
			String question = "Do you consider snowboard films to be documentaries?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "17"
		when
			Question(question_content == "Do you consider snowboard films to be documentaries?", answer == "Yes")
		then
			String movie = "Art of Flight";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "18"
		when
			Question(question_content == "Do you consider snowboard films to be documentaries?", answer == "No")
		then
			String question = "Do you want to have your face melted off from maxiumum rock?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "19"
		when
			Question(question_content == "Do you want to have your face melted off from maxiumum rock?", answer == "Yes")
		then
			String movie = "Year of the Horse";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "20"
		when
			Question(question_content == "Do you want to have your face melted off from maxiumum rock?", answer == "No")
		then
			String question = "Take it to the streets?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "21"
		when
			Question(question_content == "Take it to the streets?", answer == "Yes")
		then
			String question = "Pain or Paint?";
			String[] possible_answers = {"Pain", "Paint"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "22"
		when
			Question(question_content == "Pain or Paint?", answer == "Pain")
		then
			String movie = "Bones Brigade: An Autobiography";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "23"
		when
			Question(question_content == "Pain or Paint?", answer == "Paint")
		then
			String movie = "Exit Through the Gift Shop";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "24"
		when
			Question(question_content == "Take it to the streets?", answer == "No")
		then
			String question = "Do you want to see how ridiculous religion can be?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "25"
		when
			Question(question_content == "Do you want to see how ridiculous religion can be?", answer == "Yes")
		then
			String movie = "Religulous";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "26"
		when
			Question(question_content == "Do you want to see how ridiculous religion can be?", answer == "No")
		then
			String question = "Are you a Woody Allen fan? Or would you like to become one?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "27"
		when
			Question(question_content == "Are you a Woody Allen fan? Or would you like to become one?", answer == "Yes")
		then
			String movie = "Woody Allen: A Documentary";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "28"
		when
			Question(question_content == "Are you a Woody Allen fan? Or would you like to become one?", answer == "No")
		then
			String question = "Do subtitles bother you?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		    Question q = new Question(question, gui.answer);
			insert(q);
end

rule "29"
		when
			Question(question_content == "Do subtitles bother you?", answer == "Yes")
		then
			String movie = "Grizzly man";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "30"
		when
			Question(question_content == "Do subtitles bother you?", answer == "No")
		then
			String movie = "Man on Wire";
			gui.insertQuestionAndSetAnswer(movie, null, true);
end

rule "31"
		when
			Question(question_content == "What about documentary?", answer == "No")
		then
			String question = "Monsters, murderers and madness?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);
end

rule "32"
		when
			Question(question_content == "Monsters, murderers and madness?", answer == "Yes")
		then
			String question = "Should there be a blood saoked chainsaw at some point?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);

rule "33"
	when
			Question(question_content == "Should there be a blood saoked chainsaw at some point?", answer == "Yes")
		then
			String movie = "The Evil dead";
			gui.insertQuestionAndSetAnswer(movie, null, true);
		
rule "34"
	when
		Question(question_content == "Should there be a blood saoked chainsaw at some point?", answer == "No")
	then
		String question = "Three parts classic horror, one part something new?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "35"
	when
		Question(question_content == "Three parts classic horror, one part something new?", answer == "Yes")
	then
		String movie = "Cabin in the woods";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "36"
	when
		Question(question_content == "Three parts classic horror, one part something new?", answer == "No")
	then
		String question = "Do abandoned asylums scare the sense out of you?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "37"
	when
		Question(question_content == "Do abandoned asylums scare the sense out of you?", answer == "Yes")
	then
		String movie = "Session 9";
		gui.insertQuestionAndSetAnswer(movie, null, true);
	
rule "38"
	when
		Question(question_content == "Do abandoned asylums scare the sense out of you?", answer == "No")
	then
		String movie = "Insidious";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "39"
		when
			Question(question_content == "Monsters, murderers and madness?", answer == "No")
		then
			String question = "Are you in the mood to laugh?";
			String[] possible_answers = {"Yes", "No"};
			gui.insertQuestionAndSetAnswer(question, possible_answers, false);
			Question q = new Question(question, gui.answer);
			insert(q);

rule "40"
	when
		Question(question_content == "Are you in the mood to laugh?", answer == "Yes")
	then
		String question = "Do you want some drama with your laughter?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "41"
	when
		Question(question_content == "Do you want some drama with your laughter?", answer == "No")
	then
		String question = "Do you mind it when people break out singing?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "42"
	when
		Question(question_content == "Do you mind it when people break out singing?", answer == "Yes")
	then
		String movie = "Happy Gilmore";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "43"
	when
		Question(question_content == "Do you mind it when people break out singing?", answer == "No")
	then
		String question = "Do you find clever worldplay entertaining?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "44"
	when
		Question(question_content == "Do you find clever worldplay entertaining?", answer == "Yes")
	then
		String movie = "Duck Soup";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "45"
	when
		Question(question_content == "Do you find clever worldplay entertaining?", answer == "No")
	then
		String movie = "Ferris Bueller's Day Off";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "46"
	when
		Question(question_content == "Do you want some drama with your laughter?", answer == "Yes")
	then
		String question = "Are you adverse to black and white?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "47"
	when
		Question(question_content == "Are you adverse to black and white?", answer == "Yes")
	then
		String question = "Do you love Paul Newman? Do you want to?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "48"
	when
		Question(question_content == "Do you love Paul Newman? Do you want to?", answer == "Yes")
	then
		String question = "Do you want to watch something great or legendary?";
		String[] possible_answers = {"Legend", "Great"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "49"
	when
		Question(question_content == "Do you want to watch something great or legendary?", answer == "Legend")
	then
		String movie = "Butch Cassidy and the Sundance Kid";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "50"
	when
		Question(question_content == "Do you want to watch something great or legendary?", answer == "Great")
	then
		String movie = "Slap Shot";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "51"
	when
		Question(question_content == "Do you love Paul Newman? Do you want to?", answer == "No")
	then
		String question = "Gritty or pretty?";
		String[] possible_answers = {"Gritty", "Pretty"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "52"
	when
		Question(question_content == "Gritty or pretty?", answer == "Gritty")
	then
		String movie = "Transpotting";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "53"
	when
		Question(question_content == "Gritty or pretty?", answer == "Pretty")
	then
		String question = "Slow-paces quirky romantic indie?";
		String[] possible_answers = {"Yes", "No"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "54"
	when
		Question(question_content == "Slow-paces quirky romantic indie?", answer == "Yes")
	then
		String movie = "Lost in Translation";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "55"
	when
		Question(question_content == "Slow-paces quirky romantic indie?", answer == "No")
	then
		String movie = "Big Fish";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "56"
	when
		Question(question_content == "Are you adverse to black and white?", answer == "No")
	then
		String question = "Do you like your humor to e less or more lewd?";
		String[] possible_answers = {"Less", "More"};
		gui.insertQuestionAndSetAnswer(question, possible_answers, false);
		Question q = new Question(question, gui.answer);
		insert(q);

rule "57"
	when
		Question(question_content == "Do you like your humor to e less or more lewd?", answer == "Less")
	then
		String movie = "ManHattan";
		gui.insertQuestionAndSetAnswer(movie, null, true);

rule "58"
	when
		Question(question_content == "Do you like your humor to e less or more lewd?", answer == "More")
	then
		String movie = "Clerks";
		gui.insertQuestionAndSetAnswer(movie, null, true);